In [ ]:
import numpy as np 

In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[6,7],[8,9]])
print(arr1.shape)
print(arr2.shape)
arr=np.concatenate((arr1,arr2))
print(arr)

In [ ]:
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

In [ ]:
arr=np.stack((arr1,arr2),axis=1)
print(arr)

In [ ]:
print(arr)
arr=np.dstack((arr1,arr2))
print(arr)

In [ ]:
arr=np.array([1,2,3,4,5])
newarr=np.array_split(arr,4)
print(newarr)

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr=np.array_split(arr,4)
print(newarr)

In [ ]:
print(arr)
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr=np.array_split(arr,4,axis=1)
print(newarr)

In [32]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr=np.where(arr==4)
print(newarr)

(array([1], dtype=int64), array([1], dtype=int64))


In [35]:
arr = np.array([1, 2, 3, 5, 5, 4, 4])
newarr=np.where(arr==1)
print(newarr)

(array([0], dtype=int64),)


In [51]:
newarr=np.searchsorted(arr,[9,5,8],side='right')
print(newarr)

[7 7 7]


In [54]:
arr = np.array([1, 2, 3, 5, 5, 4, 4,8,4,3,2,9,0])
newarr=np.sort(arr)
print(newarr)

[0 1 2 2 3 3 4 4 4 5 5 8 9]


In [55]:
print(np.searchsorted(newarr,5))

9


In [56]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [57]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr=arr[x]
print(newarr)

[41 43]


In [59]:
arr=np.array([41,42,43,44,45,2,12,32,44,22,12,221,46,46,47])
filt_arr=[]
for element in arr:
    if element >42:
        filt_arr.append(True)
    else:
        filt_arr.append(False)
newarr=arr[filt_arr]
print(arr)
print(filt_arr)
print(newarr)

[ 41  42  43  44  45   2  12  32  44  22  12 221  46  46  47]
[False, False, True, True, True, False, False, False, True, False, False, True, True, True, True]
[ 43  44  45  44 221  46  46  47]


In [62]:
import random 
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
filt_arr=[]
for element in arr:
    if element%2==0:
        filt_arr.append(True)
    else:
        filt_arr.append(False)
newarr=arr[filt_arr]
print(arr)
print(filt_arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10 12 14 16 18 20]


In [63]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
filt_arr=arr%2==0
newarr=arr[filt_arr]
print(filt_arr)
print(newarr)

[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]
[ 2  4  6  8 10 12 14 16 18 20]
