In [1]:
import numpy as np 

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
np.__version__

'1.25.2'

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr=np.array((1,2,3,4,5,6))
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
#   0-D array in numpy
arr=np.array(42)
print(arr)

42


In [7]:
#   1-D array in numpy
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
#   2-D array in numpy
arr=np.array([[1,2,3,4],[2,3,4,1]])
print(arr)

[[1 2 3 4]
 [2 3 4 1]]


In [9]:
#   3-D array in numpy
arr=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [1 2 3]]]


In [10]:
a=np.array(42)  #0-D array
b=np.array([1,2,3,4,5]) #1-D array
c=np.array([[1,2,3],[2,3,4]])   #2-D array
d=np.array([[[1,2,3],[3,2,1]],[[4,5,6],[1,2,3]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensio :',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensio : 5


In [12]:
arr=np.array([2,4,3,1,5,7])
print(arr[0])

2


In [13]:
print(arr[1])

4


In [14]:
print(arr[3]+arr[4])

6


In [15]:
arr=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr[1,1])

5


In [16]:
print(arr[1,4])

8


In [17]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [18]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,1]])
print(arr[1,-1])

1


In [19]:
arr=np.array([1,2,3,4,5])
print(arr[1:5])

[2 3 4 5]


In [20]:
print(arr[3:])

[4 5]


In [21]:
print(arr[:4])

[1 2 3 4]


In [22]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[-3:-1])

[7 8]


In [23]:
print(arr[::2])

[1 3 5 7 9]


In [24]:
arr=np.array([[1,2,3,4,5,6,3,2,1,5],[1,2,6,7,10,5,6,7,8,9]])
print(arr[0,1:7])

[2 3 4 5 6 3]


In [25]:
print(arr[1,1:6])

[ 2  6  7 10  5]


In [26]:
arr

array([[ 1,  2,  3,  4,  5,  6,  3,  2,  1,  5],
       [ 1,  2,  6,  7, 10,  5,  6,  7,  8,  9]])

In [27]:
print(arr[0:2,5])

[6 5]


In [28]:
print(arr.dtype)

int32


In [29]:
arr=np.array(['apple','mango','papaya'])
print(arr.dtype)

<U6


In [30]:
arr=np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [31]:
arr=np.array([1,2,3,4,5],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [32]:
arr=np.array([1.1,2.1,3.4,4.2,5.6])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4 5]
int32


In [33]:
newarr=arr.astype('int')
print(newarr)
print(newarr.dtype)

[1 2 3 4 5]
int32


In [34]:
arr=np.array([1,2,3,4,5,6,7])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5  6  7]
[1 2 3 4 5 6 7]


In [35]:
arr=np.array([1,2,3,4,5,6,7,8,9])
x=arr.view()
arr[0]=42
print(arr)
print(x)


[42  2  3  4  5  6  7  8  9]
[42  2  3  4  5  6  7  8  9]


In [36]:
arr=np.array([1,2,3,4,5,6,7,8,9])
x=arr.view()
x[0]=10
print(arr)
print(x)

[10  2  3  4  5  6  7  8  9]
[10  2  3  4  5  6  7  8  9]


In [37]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [38]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [39]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
newarr=arr.reshape(3,5)
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [40]:
newarr=arr.reshape(5,3,1)
print(newarr)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]]


In [41]:
arr=np.array([1,2,3,4,5,6,7,8,7])
newarr=arr.reshape(3,3,-1)
print(newarr)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [7]]]


In [42]:
print(arr.reshape(3,3).base)

[1 2 3 4 5 6 7 8 7]


In [43]:
newarr=arr.reshape(3,3,-1)
print(newarr)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [7]]]


In [44]:
arr=np.array([[1,2,3,4],[2,4,3,5]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 2 4 3 5]


In [45]:
arr=np.array([1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


In [46]:
arr=np.array([[1,2,3,4,5],[4,5,3,2,1]])
for i in arr:
    print(i)

[1 2 3 4 5]
[4 5 3 2 1]


In [47]:
for i in arr:
    for j in i:
        print(j,end=" ")

1 2 3 4 5 4 5 3 2 1 

In [48]:
arr=np.array([[[1,2,3],[3,2,4]],[[2,5,4],[6,5,3]]])
for i in arr:
    print(i)

[[1 2 3]
 [3 2 4]]
[[2 5 4]
 [6 5 3]]


In [49]:
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
3
2
4
2
5
4
6
5
3


In [50]:
arr=np.array([[[1,2],[2,4]],[[3,5],[6,5]]])
for i in np.nditer(arr):
    print(i)

1
2
2
4
3
5
6
5


In [51]:
arr=np.array([1,2,3])
for i in np.nditer(arr,op_dtypes=['U'],flags=['buffered']):
    print(i)

1
2
3


In [52]:
arr=np.array([[1,2,3,4],[2,3,1,5]])
for i in np.nditer(arr,flags=['buffered'],op_dtypes=['U']):
    print(i)

1
2
3
4
2
3
1
5


In [53]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(arr[::,::2]):
    print(i)

1
3
5
7


In [54]:
arr=np.array([[[1,2,3,4,5],[2,3,1,4,3]],[[1,4,3,2,4],[4,5,6,7,1]]])
for idx,i in np.ndenumerate(arr):
    print(idx,i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 2
(0, 1, 1) 3
(0, 1, 2) 1
(0, 1, 3) 4
(0, 1, 4) 3
(1, 0, 0) 1
(1, 0, 1) 4
(1, 0, 2) 3
(1, 0, 3) 2
(1, 0, 4) 4
(1, 1, 0) 4
(1, 1, 1) 5
(1, 1, 2) 6
(1, 1, 3) 7
(1, 1, 4) 1


In [55]:
arr1=np.array([1,2,3,4])
arr2=np.array([2,1,3])
print(arr1.dtype)
print(arr2.dtype)
arr=np.concatenate((arr1,arr2))
print(arr)
print(arr.dtype)

int32
int32
[1 2 3 4 2 1 3]
int32


In [56]:
arr1=np.array([[1,2,3],[2,3,4]])
arr2=np.array([[8,9,3],[4,3,6]])
arr=np.concatenate((arr1,arr2))
print(arr)

[[1 2 3]
 [2 3 4]
 [8 9 3]
 [4 3 6]]


axis=1 means join along rows

In [57]:
arr1=np.array([[1,2,3],[2,3,4]])
arr2=np.array([[8,9,3],[4,3,6]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 3 8 9 3]
 [2 3 4 4 3 6]]


In [58]:
arr1=np.array([[1,2,3],[2,3,4]])
arr2=np.array([[8,9,3],[4,3,6]])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[[1 2 3]
  [8 9 3]]

 [[2 3 4]
  [4 3 6]]]


In [59]:
#hstack() to stack along rows
arr1=np.array([[1,2,3],[2,3,4]])
arr2=np.array([[8,9,3],[4,3,6]])
arr=np.hstack((arr1,arr2))
print(arr)

[[1 2 3 8 9 3]
 [2 3 4 4 3 6]]


In [60]:
#   vstack() to stack along columns
arr1=np.array([[1,2,3],[2,3,4]])
arr2=np.array([[8,9,3],[4,3,6]])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [2 3 4]
 [8 9 3]
 [4 3 6]]


In [61]:
arr1=np.array([[1,2,3],[2,3,4]])
arr2=np.array([[8,9,3],[4,3,6]])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 8]
  [2 9]
  [3 3]]

 [[2 4]
  [3 3]
  [4 6]]]


In [68]:
arr1=np.array([1,2,3])
arr2=np.array([4,4,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 4 6]]


In [73]:
arr=np.array([1,2,3,4,5])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3]), array([4]), array([5])]


In [75]:
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3]), array([4]), array([5])]


In [76]:
newarr=np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5]


In [95]:
arr=np.array([[1,2,3],[3,2,8],[1,4,2],[4,5,3],[8,9,7]])
newarr=np.array_split(arr,3)
print(newarr)
newarr=np.array_split(arr,3,axis=1)
print(newarr)

[array([[1, 2, 3],
       [3, 2, 8]]), array([[1, 4, 2],
       [4, 5, 3]]), array([[8, 9, 7]])]
[array([[1],
       [3],
       [1],
       [4],
       [8]]), array([[2],
       [2],
       [4],
       [5],
       [9]]), array([[3],
       [8],
       [2],
       [3],
       [7]])]


Searching array

In [101]:
arr=np.array([1,2,3,4,8,2,3,4,1,5,8,2,9,7,4,1,2])
x=np.where(arr==2)
print(x)

(array([ 1,  5, 11, 16], dtype=int64),)


In [106]:
print(arr)
x=np.where(arr%2==0)
print(x)

[1 2 3 4 8 2 3 4 1 5 8 2 9 7 4 1 2]
(array([ 1,  3,  4,  5,  7, 10, 11, 14, 16], dtype=int64),)


In [109]:
print(arr)
x=np.where(arr%2!=1)
print(x)

[1 2 3 4 8 2 3 4 1 5 8 2 9 7 4 1 2]
(array([ 1,  3,  4,  5,  7, 10, 11, 14, 16], dtype=int64),)


In [133]:
arr=np.sort(arr)
print(arr)
x=np.searchsorted(arr,5)
print(x)

[1 3 4 5 6 8 9]
3


In [128]:
arr=np.array([1,3,4,5,6,8,9])
x=np.searchsorted(arr,5,side='right')
print(x)

4


In [131]:
arr=np.array([1,3,4,5,6,8,9])
x=np.searchsorted(arr,[2,3,7])
print(x)

[1 1 5]
