In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4])

In [4]:
x

array([1, 2, 3, 4])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.random.random(5)

array([0.8712042 , 0.6627467 , 0.61580292, 0.85212326, 0.48170705])

In [13]:
new_math=np.array([2,6,1,2,3])

In [14]:
new_ones=np.ones(5)

In [15]:
new_math + new_ones

array([3., 7., 2., 3., 4.])

In [16]:
new_ones*3

array([3., 3., 3., 3., 3.])

In [17]:
new_math[0]

2

In [18]:
new_math[1]

6

In [19]:
new_math.max()

6

In [20]:
new_math.min()

1

In [21]:
new_math.sum()

14

In [22]:
new_math

array([2, 6, 1, 2, 3])

In [23]:
#Creating N-D Arrays or Matrices

In [24]:
x=np.array([[1,2,3],[3,4,2]])

In [25]:
x

array([[1, 2, 3],
       [3, 4, 2]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.random.random((2,2))

array([[0.53465382, 0.26829443],
       [0.07888977, 0.17279789]])

In [37]:
y=np.array([[2,4,3],[4,6,5]])

In [38]:
y

array([[2, 4, 3],
       [4, 6, 5]])

In [39]:
x+y

array([[ 3,  6,  6],
       [ 7, 10,  7]])

In [43]:
x

array([[1, 2, 3],
       [3, 4, 2]])

In [44]:
x.dot(y)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [47]:
y[1,2]

5

In [49]:
# Reshaping Arrays

In [50]:
new_data=np.array([1,2,3,4,5,6])

In [52]:
new_data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
new_data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
x=np.array([[[10,12],[23,21]],[[12,34],[44,32]]])

In [60]:
x

array([[[10, 12],
        [23, 21]],

       [[12, 34],
        [44, 32]]])