In [2]:
import cv2
import numpy as np

In [3]:
img=cv2.imread('13.png')
re_img=cv2.resize(img,(600,600))
cv2.imshow('Akash',re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
print(img)

[[[247 247 247]
  [247 247 247]
  [247 247 247]
  ...
  [247 247 247]
  [247 247 247]
  [247 247 247]]

 [[247 247 247]
  [247 247 247]
  [247 247 247]
  ...
  [247 247 247]
  [247 247 247]
  [247 247 247]]

 [[247 247 247]
  [247 247 247]
  [247 247 247]
  ...
  [247 247 247]
  [247 247 247]
  [247 247 247]]

 ...

 [[247 236 225]
  [248 237 226]
  [250 239 228]
  ...
  [250 239 227]
  [248 237 225]
  [248 237 225]]

 [[248 237 226]
  [248 237 226]
  [248 237 226]
  ...
  [248 237 225]
  [249 238 226]
  [250 239 227]]

 [[247 236 225]
  [250 239 228]
  [248 237 226]
  ...
  [248 237 225]
  [248 237 225]
  [247 236 224]]]


In [5]:
img=cv2.imread('13.png')
re_img=cv2.resize(img,(400,500))
h=np.hstack((re_img,re_img))
cv2.imshow('Akash',h)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
img=cv2.imread('17.png')
img2=cv2.imread('12.png')
re_img=cv2.resize(img,(200,200))
re_img2=cv2.resize(img2,(200,200))
h=np.hstack((re_img,re_img2))
v=np.vstack((h,h))
cv2.imshow('Akash',v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
import os

In [8]:
list_name=os.listdir(r"H:\Python+DS\Computer_Vision\wscube_openCV")
list_name

['11.png',
 '12.png',
 '13.png',
 '14.png',
 '15.png',
 '16.png',
 '17.png',
 '18.png',
 '19.png',
 'cv1.ipynb',
 'cv2.ipynb']

In [12]:
list_name=os.listdir(r"H:\Python+DS\Computer_Vision\wscube_openCV")

for name in list_name:
    path="H:\\Python+DS\\Computer_Vision\\wscube_openCV"
    img_name=path+"\\"+name
    img=cv2.imread(img_name)
    img=cv2.resize(img,(500,600))
    cv2.imshow('Akash',img)
    cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
